services:
  - type: web
    name: fish-record
    env: node
    plan: free
    buildCommand: npm cache clean --force && npm install --production=false && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false